kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: bitwarden
  name: bitwarden-amd64
  namespace: tedy
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      k8s-app: bitwarden
  template:
    metadata:
      labels:
        k8s-app: bitwarden
    spec:
      terminationGracePeriodSeconds: 2
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/arch: amd64
        kubernetes.io/hostname: tedy-desktop-debian
      containers:
        - name: bitwarden
          image: bitwardenrs/server:1.14.2
          resources:
            limits:
              memory: "50Mi"
              cpu: "50m"
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 3012
              protocol: TCP
          env:
            - name: WEBSOCKET_ENABLED
              value: "true"
            - name: DOMAIN
              value: "https://bitwarden.stoicatedy.ovh"
            - name: YUBICO_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: YUBICO_CLIENT_ID
                  name: bitwarden-secret
            - name: YUBICO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: YUBICO_SECRET_KEY
                  name: bitwarden-secret
            - name: SIGNUPS_ALLOWED
              value: "true"
            - name: SHOW_PASSWORD_HINT
              value: "false"
          volumeMounts:
            - name: data
              mountPath: /data
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 30
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bitwarden
